### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by sanket2000** [sanket2000/proctoring#1]
# Make a chrome extension to echo your 
- [ ] video 
- [ ] audio
- [ ] desktop capture which includes
- [ ] all chrome tab info
- [ ] system apps info
- [ ] Notifications

Deadline: 26/06/2021 Saturday

**Comment by sanket2000** [comment]
Ganpati bappa moriya....

Lets goo guys

**Comment by rithwik00** [comment]
Yess Lets do it 🔥
🙏

**Comment by sanket2000** [comment]
Progress Stalled, Closing...
